name: 9191md
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run scraper script
      run: |
        python 9191md.py  # 运行抓取视频数据的 Python 脚本

    - name: Run scraper script
      run: |
        python lziapi.py  # 运行抓取视频数据的 Python 脚本



    - name: Configure Git for commit
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'your-email@example.com'

    - name: Commit and push the files
      run: |
        git add *.txt
        git commit -m "Add scraped video data files"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
